# Generated by Django 4.1.5 on 2023-05-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='predicted_results',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ques_ans', models.TextField()),
                ('marks', models.CharField(max_length=100)),
            ],
        ),
    ]
