# Generated by Django 4.1.5 on 2023-05-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_questions_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions_random',
            name='marks',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
